apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplan-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readinessState
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  ingresses:
    - "https://oppfolgingsplan-backend.intern.dev.nav.no"
  resources:
    limits:
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 400Mi
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: oppfolgingsplan-frontend
    outbound:
      external:
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "ereg-services-q1.dev-fss-pub.nais.io"
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: dev-gcp
        - application: syfobrukertilgang
          namespace: team-esyfo
          cluster: dev-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://oppfolgingsplan-backend.intern.dev.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        name: oppfolgingsplan-backend-db-instance
        databases:
          - name: oppfolgingsplan-backend-db
            envVarPrefix: DB
            users:
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
    - name: KRR_URL
      value: https://digdir-krr-proxy.intern.dev.nav.no/rest/v1/person
    - name: KRR_SCOPE
      value: dev-gcp.team-rocket.digdir-krr-proxy
    - name: SYFOBRUKERTILGANG_URL
      value: http://syfobrukertilgang
    - name: SYFOBRUKERTILGANG_ID
      value: dev-gcp:team-esyfo:syfobrukertilgang
    - name: OPPFOLGINGSPLAN_FRONTEND_CLIENT_ID
      value: dev-gcp:team-esyfo:oppfolgingsplan-frontend
    - name: NARMESTELEDER_URL
      value: http://isnarmesteleder.teamsykefravr
    - name: NARMESTELEDER_CLIENT_ID
      value: dev-gcp:teamsykefravr:isnarmesteleder
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: EREG_URL
      value: https://ereg-services-q1.dev-fss-pub.nais.io
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: dev-gcp.teamsykefravr.istilgangskontroll
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: AAREG_SERVICES_URL
      value: https://aareg-services-q1.dev.intern.nav.no/api
    - name: FELLESKODEVERK_URL
      value: https://kodeverk-api.nav.no/api/v1
  redis:
    - instance: oppfolgingsplan
      access: readwrite
