apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: oppfolgingsplan-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readinessState
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
    - "https://oppfolgingsplan-backend.intern.nav.no"
  resources:
    limits:
      cpu: 3000m
      memory: 3060Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: oppfolgingsplan-frontend
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "ereg-services.prod-fss-pub.nais.io"
      rules:
        - application: digdir-krr-proxy
          namespace: team-rocket
          cluster: prod-gcp
        - application: syfobrukertilgang
          namespace: team-esyfo
          cluster: prod-gcp
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: prod-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://oppfolgingsplan-backend.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-1-3840
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        name: oppfolgingsplan-backend-db-instance
        databases:
          - name: oppfolgingsplan-backend-db
            envVarPrefix: DB
            users:
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
    - name: KRR_URL
      value: https://digdir-krr-proxy.intern.nav.no/rest/v1/person
    - name: KRR_SCOPE
      value: api://prod-gcp.team-rocket.digdir-krr-proxy/.default
    - name: SYFOBRUKERTILGANG_URL
      value: http://syfobrukertilgang
    - name: SYFOBRUKERTILGANG_ID
      value: prod-gcp:team-esyfo:syfobrukertilgang
    - name: OPPFOLGINGSPLAN_FRONTEND_CLIENT_ID
      value: prod-gcp:team-esyfo:oppfolgingsplan-frontend
    - name: NARMESTELEDER_URL
      value: http://isnarmesteleder.teamsykefravr
    - name: NARMESTELEDER_CLIENT_ID
      value: prod-gcp:teamsykefravr:isnarmesteleder
    - name: PDL_CLIENT_ID
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: EREG_URL
      value: https://ereg-services.prod-fss-pub.nais.io
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: api://prod-gcp.teamsykefravr.istilgangskontroll/.default
    - name: ISTILGANGSKONTROLL_URL
      value: http://istilgangskontroll.teamsykefravr
    - name: AAREG_SERVICES_URL
      value: https://aareg-services.prod-fss-pub.nais.io
    - name: FELLESKODEVERK_URL
      value: https://kodeverk-api.nav.no/api/v1
    - name: FELLESKODEVERK_SCOPE
      value: api://prod-gcp.team-rocket.kodeverk-api/.default
    - name: AAREG_SCOPE
      value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
  valkey:
    - instance: oppfolgingsplan
      access: readwrite
