name: Build & Deploy
on: push

jobs:
  boot-jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/boot-jar-app.yaml@executable-gradlew
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: oppfolgingsplan-backend
