name: Deploy Redis
on:
  push:
    paths: ['nais/redis-dev.yaml', 'nais/redis-prod.yaml']
  workflow_dispatch:

jobs:
  deploy-redis-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/redis-dev.yaml

  deploy-redis-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-redis-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/redis-prod.yaml
